package com.parkee.assets.repo

object CountryNameProvider {
    private val countryName = mapOf(
        "AED" to "United Arab Emirates dirham",
        "ARS" to "Argentine peso",
        "AUD" to "Australian dollar",
        "BDT" to "Bangladeshi taka",
        "BGN" to "Bulgarian lev",
        "BRL" to "Brazilian real",
        "BWP" to "Botswana pula",
        "CAD" to "Canadian dollar",
        "CHF" to "Swiss franc",
        "CLP" to "Chilean peso",
        "CNY" to "Chinese yuan",
        "COP" to "Colombian peso",
        "CRC" to "Costa Rican colon",
        "CZK" to "Czech koruna",
        "DKK" to "Danish krone",
        "EGP" to "Egyptian pound",
        "EUR" to "Euro",
        "GBP" to "British pound",
        "GEL" to "Georgian lari",
        "GHS" to "Ghanaian cedi",
        "HKD" to "Hong Kong dollar",
        "HRK" to "Croatioan kuna",
        "HUF" to "Hungarian forint",
        "IDR" to "Indonesian rupiah",
        "ILS" to "Israeli shekel",
        "INR" to "Indian rupee",
        "JPY" to "Japaneses yen",
        "KES" to "Kenyan shilling",
        "KRW" to "South Korean won",
        "LKR" to "Sri Lankan rupee",
        "MAD" to "Moroccan dirham",
        "MXN" to "Mexican peso",
        "MYR" to "Malaysian ringgit",
        "NGN" to "Nigerian naira",
        "NOK" to "Norwegian krone",
        "NPR" to "Nepalese rupee",
        "NZD" to "New Zealand dollar",
        "PEN" to "Peruvian neuvo sol",
        "PHP" to "Philippine peso",
        "PKR" to "Pakistani rupee",
        "PLN" to "Polish zloty",
        "RON" to "Romanian leu",
        "RUB" to "Russian rouble",
        "SEK" to "Swedish krona",
        "SGD" to "Singapore dollar",
        "THB" to "Thai baht",
        "TRY" to "Turkish lira",
        "TZS" to "Tanzania shilling",
        "UAH" to "Ukrainian hryvnia",
        "UGX" to "Ugandan shilling",
        "USD" to "United States dollar",
        "UYU" to "Uruguayan peso",
        "VND" to "Vietnamese dong",
        "XOF" to "West African CFA franc",
        "ZAR" to "South African rand",
        "ZMW" to "Zambian kwacha",
        "United Arab Emirates dirham" to "AED",
        "Argentine peso" to "ARS",
        "Australian dollar" to "AUD",
        "Bangladeshi taka" to "BDT",
        "Bulgarian lev" to "BGN",
        "Brazilian real" to "BRL",
        "Botswana pula" to "BWP",
        "Canadian dollar" to "CAD",
        "Swiss franc" to "CHF",
        "Chilean peso" to "CLP",
        "Chinese yuan" to "CNY",
        "Colombian peso" to "COP",
        "Costa Rican colon" to "CRC",
        "Czech koruna" to "CZK",
        "Danish krone" to "DKK",
        "Egyptian pound" to "EGP",
        "Euro" to "EUR",
        "British pound" to "GBP",
        "Georgian lari" to "GEL",
        "Ghanaian cedi" to "GHS",
        "Hong Kong dollar" to "HKD",
        "Croatioan kuna" to "HRK",
        "Hungarian forint" to "HUF",
        "Indonesian rupiah" to "IDR",
        "Israeli shekel" to "ILS",
        "Indian rupee" to "INR",
        "Japaneses yen" to "JPY",
        "Kenyan shilling" to "KES",
        "South Korean won" to "KRW",
        "Sri Lankan rupee" to "LKR",
        "Moroccan dirham" to "MAD",
        "Mexican peso" to "MXN",
        "Malaysian ringgit" to "MYR",
        "Nigerian naira" to "NGN",
        "Norwegian krone" to "NOK",
        "Nepalese rupee" to "NPR",
        "New Zealand dollar" to "NZD",
        "Peruvian neuvo sol" to "PEN",
        "Philippine peso" to "PHP",
        "Pakistani rupee" to "PKR",
        "Polish zloty" to "PLN",
        "Romanian leu" to "RON",
        "Russian rouble" to "RUB",
        "Swedish krona" to "SEK",
        "Singapore dollar" to "SGD",
        "Thai baht" to "THB",
        "Turkish lira" to "TRY",
        "Tanzania shilling" to "TZS",
        "Ukrainian hryvnia" to "UAH",
        "Ugandan shilling" to "UGX",
        "United States dollar" to "USD",
        "Uruguayan peso" to "UYU",
        "Vietnamese dong" to "VND",
        "West African CFA franc" to "XOF",
        "South African rand" to "ZAR",
        "Zambian kwacha" to  "ZMW"
    )

    fun getCountryName(currency: String): String? = countryName[currency]
}